@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Oct 13 21:10:15 +0800 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim selectTOP6_tb_behav -key {Behavioral:sim_1:Functional:selectTOP6_tb} -tclbatch selectTOP6_tb.tcl -view D:/1111/DCCDL/VIVADO/Lab2/selectTOP6/selectTOP6_tb_behav.wcfg -log simulate.log"
call xsim  selectTOP6_tb_behav -key {Behavioral:sim_1:Functional:selectTOP6_tb} -tclbatch selectTOP6_tb.tcl -view D:/1111/DCCDL/VIVADO/Lab2/selectTOP6/selectTOP6_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
