@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jan 03 16:39:56 +0800 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim FFT_SDF_Radix4_64point_tb1_behav -key {Behavioral:sim_1:Functional:FFT_SDF_Radix4_64point_tb1} -tclbatch FFT_SDF_Radix4_64point_tb1.tcl -log simulate.log"
call xsim  FFT_SDF_Radix4_64point_tb1_behav -key {Behavioral:sim_1:Functional:FFT_SDF_Radix4_64point_tb1} -tclbatch FFT_SDF_Radix4_64point_tb1.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
