@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jan 04 21:43:27 +0800 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim stage1_tb_behav -key {Behavioral:sim_1:Functional:stage1_tb} -tclbatch stage1_tb.tcl -view D:/1111/DCCDL/final project/vivado/it_work/it_works/it_works.srcs/sim_1/imports/SDF_64points_FFT/butterfly_test_tb_time_synth.wcfg -log simulate.log"
call xsim  stage1_tb_behav -key {Behavioral:sim_1:Functional:stage1_tb} -tclbatch stage1_tb.tcl -view D:/1111/DCCDL/final project/vivado/it_work/it_works/it_works.srcs/sim_1/imports/SDF_64points_FFT/butterfly_test_tb_time_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
