webtalk_init -webtalk_dir E:/1111/DCCDL/VIVADO/lab6/fft_pm6/fft.sim/sim_1/impl/timing/xsim/xsim.dir/stage1_tb_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Dec  5 00:57:31 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212567245_0_0_601" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "98803d31-8c5c-4f7f-8830-1400ffb31c02" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2394abec491d48f08ebb807feb281ab5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "64" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.86_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "49684_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1614674539 -regid "212567245_0_0_601" -xml E:/1111/DCCDL/VIVADO/lab6/fft_pm6/fft.sim/sim_1/impl/timing/xsim/xsim.dir/stage1_tb_time_impl/webtalk/usage_statistics_ext_xsim.xml -html E:/1111/DCCDL/VIVADO/lab6/fft_pm6/fft.sim/sim_1/impl/timing/xsim/xsim.dir/stage1_tb_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm E:/1111/DCCDL/VIVADO/lab6/fft_pm6/fft.sim/sim_1/impl/timing/xsim/xsim.dir/stage1_tb_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
